{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.routeName | default (include "fluxbase.fullname" .) }}
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.gateway.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.gateway.annotations }}
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.gateway.parentRefs }}
  parentRefs:
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
    - matches:
        - path:
            type: {{ .Values.gateway.pathType }}
            value: {{ .Values.gateway.path }}
      backendRefs:
        - name: {{ include "fluxbase.fullname" . }}
          port: {{ .Values.service.ports.http }}
{{- end }}
