{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluxbase.fullname" . }}
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.persistence.annotations }}
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.persistence.selector }}
  selector: {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.functions.persistence.enabled (not .Values.functions.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluxbase.fullname" . }}-functions
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.functions.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.functions.persistence.annotations }}
    {{- toYaml .Values.functions.persistence.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.functions.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.functions.persistence.size | quote }}
  {{- if .Values.functions.persistence.storageClass }}
  storageClassName: {{ .Values.functions.persistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.functions.persistence.selector }}
  selector: {{- toYaml .Values.functions.persistence.selector | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.migrations.persistence.enabled (not .Values.migrations.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluxbase.fullname" . }}-migrations
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.migrations.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.migrations.persistence.annotations }}
    {{- toYaml .Values.migrations.persistence.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.migrations.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.migrations.persistence.size | quote }}
  {{- if .Values.migrations.persistence.storageClass }}
  storageClassName: {{ .Values.migrations.persistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.migrations.persistence.selector }}
  selector: {{- toYaml .Values.migrations.persistence.selector | nindent 4 }}
  {{- end }}
{{- end }}
