{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluxbase.fullname" . }}
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.persistence.annotations }}
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.persistence.selector }}
  selector: {{- toYaml .Values.persistence.selector | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.functionsPersistence.enabled (not .Values.functionsPersistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluxbase.fullname" . }}-functions
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.functionsPersistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.functionsPersistence.annotations }}
    {{- toYaml .Values.functionsPersistence.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.functionsPersistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.functionsPersistence.size | quote }}
  {{- if .Values.functionsPersistence.storageClass }}
  storageClassName: {{ .Values.functionsPersistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.functionsPersistence.selector }}
  selector: {{- toYaml .Values.functionsPersistence.selector | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.migrationsPersistence.enabled (not .Values.migrationsPersistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fluxbase.fullname" . }}-migrations
  namespace: {{ include "fluxbase.namespace" . | quote }}
  labels: {{- include "fluxbase.labels" . | nindent 4 }}
  {{- if or .Values.migrationsPersistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.migrationsPersistence.annotations }}
    {{- toYaml .Values.migrationsPersistence.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes: {{- toYaml .Values.migrationsPersistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.migrationsPersistence.size | quote }}
  {{- if .Values.migrationsPersistence.storageClass }}
  storageClassName: {{ .Values.migrationsPersistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.migrationsPersistence.selector }}
  selector: {{- toYaml .Values.migrationsPersistence.selector | nindent 4 }}
  {{- end }}
{{- end }}
